### ISSUE TITLE
Signature Version 2 is used to authenticate for AWS S3   will be deprecated .

### ISSUE THREAD

**Issue by varusan** [fujiwara/stretcher#23]
Signature Version 2 is being deprecated in Amazon S3, and the final support for Signature Version 2 ends on June 24, 2019. After June 24, 2019, Amazon S3 will only accept API requests that are signed using Signature Version 4.

- https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingAWSSDK.html#UsingAWSSDK-sig2-deprecation

Signature Version 2 is used in goamz.(which is imported with stretcher.) 
https://github.com/AdRoll/goamz/blob/master/s3/s3.go#L99

We should use Official AWS SDK for Go.

**Comment by fujiwara** [comment]
Thank you for reporting.
I released v1.0.0-rc0 which use aws-sdk-go. https://github.com/fujiwara/stretcher/releases/tag/v1.0.0-rc0 .

Please try it.

**Comment by varusan** [comment]
Thank you for your quick response.  I'll try it.

**Comment by varusan** [comment]
We confirmed that it had been successfully deployed used v1.0.0-rc0.

**Comment by fujiwara** [comment]
Thank you for the confirmation. I'll relase v1.0.0 in this weekend.
