### ISSUE TITLE
Unfinished stdout when archive contains many files

### ISSUE THREAD

**Issue by hsbt** [fujiwara/stretcher#8]
(Sorry, I can't describe this situation with english)

v0.2.1-5-g22fa01d で大量のファイル(60000程度)を含む tar.gz を streatcher のデプロイ対象のアーカイブファイルとして指定すると、stdout が途中で切れてしまうようです。 post hook, success hook に登録されているコマンドは実行されているので、表示の問題と思います。

**Comment by hsbt** [comment]
なお、アーカイブのファイルが大量であっても、rsync で更新する対象が少ない場合はフックを含む全ての処理が stdout に表示されることを確認しています。

**Comment by fujiwara** [comment]
手元で5万ファイル程度含まれるtar.gzを処理してみましたが、再現できませんでした。
systemd(journald?)から実行した場合でなく、terminalでstertcherコマンドを実行した場合でも途切れるでしょうか?

```
$ echo [manifest_url] | stretcher > stretcher.log 2>&1
```

**Comment by hsbt** [comment]
https://twitter.com/fujiwara/status/667613879535468544 も含めて調査ありがとうございます。

CentOS 7.1 かつ v0.2.1-5-g22fa01d の stretcher で検証したところ

 * RateLimitBurst=0 なし、systemd 配下 -> 途切れる
 * RateLimitBurst=0 あり、systemd 配下 -> 最後まで出力される
 * terminal で実行 -> 最後まで出力される

という状態になり無事解決できました。なお、 v0.1.3 でも同じ挙動でした。
